ajaxtest/urls.py
from django.urls import path
from . import views

#https://qiita.com/kkkei257/items/b3292b443699ecfb148f

app_name = 'ajaxtest'
urlpatterns = [
    path(r'', views.index, name='index'),
    # 以下を追記(views.pyのwrite()関数にデータを送信できるようにする)
    path("ajax/", views.write, name="write"),
]

myapp/urls.py
from django.urls import path
from . import views

#views(html)を呼び出す。空urlの時(つまりデフォルト画面)にtest2.htmlを表示する。
#pkはプライマリーキー。つまりファイルを一意に指定する主キー。これを送るとファイルごとに管理可能となる。
app_name='myapp'
urlpatterns=[
    path('',views.test2,name="test2"),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('histtest.png/<int:pk>/', views.histtests, name='histtest'),
]

t/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('myapp.urls')),
    path('freetest/',include('ajaxtest.urls'))
]
#include以下で、httpなどのurlの続きの処理はinclude以下のファイルに任せることができる。
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/views.py
from django.shortcuts import get_object_or_404, render
from .models import FileUpLoad
from django_pandas.io import pd
import io
import numpy as np
import matplotlib.pyplot as plt
from django.http import HttpResponse
import base64
import matplotlib
matplotlib.use('Agg')

# Create your views here.
#viewにて普通のプログラミングっぽいのが可能
def test2(req):
    file_obj=FileUpLoad.objects.all()
    context={
        'file_obj':file_obj,
    }
    return render(req,'test2.html',context)
    #reqが発生した際に、htmlにcontext(modelsで定義した)を受け渡す.

def detail(req,pk):
    file_value=get_object_or_404(FileUpLoad,id=pk)
    try:
        df=pd.read_csv(file_value.upload_dir.path,index_col=0,skip_blank_lines=True,skiprows=6)
    except UnicodeDecodeError:
        df=pd.read_csv(file_value.upload_dir.path,index_col=0,encoding='cp932',skip_blank_lines=True,skiprows=6)
    #df.drop(df.index[[1,2,3,4,5,6,7,8]])
    context={
            'file_value':file_value,
            'df':df,
    }
    return render(req,'detail.html',context)

def inputdata(pk):
    file_value=get_object_or_404(FileUpLoad,id=pk)
    try:
        df=pd.read_csv(file_value.upload_dir.path,skip_blank_lines=True,index_col=0,skiprows=6) 
    except UnicodeDecodeError:
        df=pd.read_csv(file_value.upload_dir.path,skip_blank_lines=True,index_col=0,encoding='cp932',skiprows=6)
    #df.drop(df.index[[1,2,3,4,5,6,7,8]])     #データフレームから余分な行を削除
    TestName="IREF"
    df.replace(' ','',regex=True,inplace=True)
    df.set_index('Test Item',inplace=True)
    Test = df.at[TestName,'data']
    n = len(Test)
    plt.hist(Test,bins=n,color="red")
    plt.xlabel("Current (uA)")
    plt.ylabel("Counts (-)")
    plt.xlim(Test.mean()-3*Test.std()*1.1,Test.mean()+3*Test.std()*1.1)
    plt.vlines(Test.mean()+3*Test.std(),0,max(Test),color="#5F9BFF",linestyle='dashed')
    plt.vlines(Test.mean()-3*Test.std(),0,max(Test),color="#5F9BFF",linestyle='dashed')

def conv():
    #ここのBytesIOで仮想メモリ確保している
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=200)
    s = buf.getvalue()
    #https://edge.sincar.jp/web/base64-inline-image/
    s=base64.b64encode(s).decode('utf-8')
    buf.close()
    return s

def histtests(req,pk):
    file_value=get_object_or_404(FileUpLoad,id=pk)
    inputdata(pk)            #plot図の作成
    response = conv()        #png形式に変換する。
    #response = HttpResponse(png, content_type='image/png')
    context={
            'file_value':file_value,
            'response':response,
    }
    plt.cla()        #いちおう初期化する。
    return render(req,'histtest.html',context)
    
     




#----------テスト用関数-------------------------------------------------------------
def inputdata_test(pk):
    file_value=get_object_or_404(FileUpLoad,id=pk)
    '''try:
        df=pd.read_csv(file_value.upload_dir.path,index_col=0) 
    except UnicodeDecodeError:
        df=pd.read_csv(file_value.upload_dir.path,index_col=0,encoding='cp932')
        '''
    #関数をプロットできるかのテスト
    fig=plt.figure()
    ax = fig.add_subplot(111)
    x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    y = np.array([20, 90, 50, 30, 100, 80, 10, 60, 40, 70])
    plt.plot(x, y)
#-----------------------------------------------------------------------------------

templates/detail.html
<!doctype html>
<html>
        <head>
                <title>test</title>
        </head>
        <body>

            <h2>詳細データ描画</h2>
            <br>

            <a href="{% url 'myapp:test2' %}">メインに戻る</a>
            <br>

            <!-- 各インスタンス属性の要素を取得 -->
            <p>アップロード日：{{ file_value.created_at }}</p>
            <p>ダウンロード：<a href="{{ file_value.upload_dir.url }}">{{file_value.file_name }}</a></p>
            <p><a href="{% url 'myapp:histtest' pk=file_value.id %}"> ヒストグラム表示：</a></p>
            <br>

            <!-- 読み込んだCSVファイルをテーブル形式で表示 -->
            <table border="1">
                <tr>
                    <td>index</td>
                    {% for columns, item in df.iteritems %}
                        <th>{{ columns }}</th>
                    {% endfor %}
                </tr>
                {% for index, rows in df.iterrows %}
                    <tr>
                        <th>{{ index }}</th>
                        {% for row in rows %}
                            <td>{{ row }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>

        </body>
</html>

templates/freetest.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width-device-width, initial-scale=1.0" />
        <title>ajaxによる非同期通信出力テスト</title>
        <!--以下おまじない。popper,jqueryはネットから拝借しているのでそのurlを記入しないといけない。-->
        <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
           <div class="container">
            <div class="row">
                <div class="col-12">
                <div class="col-10">
                    <!--jumbotronは画面サイズの調整に使用する。-->
                    <div class="jumbotron mt-3" style="width: 100%;">
                        <font face='Impact'><h1 class="display-4">Golden Ratio calc. by AJAX & JSON!!</h1></font>
                        <hr class="my-4" />
                        <font size="5">黄金比計算シート</font><br>
                        <!-- ここから構文を書く。囲んでいれば、普通にif文など回すことができる。 -->
                        <!--<p><a href="% url 'myapp:test2' pk=file.id %"><font size=6>メインに戻る</a></p> -->
                        <br>
                        <p>数字iを入力すると、i番目とi-1番目から黄金比を計算します。</p>
                        <a href="https://ja.wikipedia.org/wiki/%E9%BB%84%E9%87%91%E6%AF%94" target="blank">wikipediaによる説明</a>
                        <br><br>
                        <input type="number" size="50" id="input_form">
                        <button type="button" onclick="clickBtn()">計算</button>
                        <br><br>
                        <font size="4"><div id='result'>黄金比：</div></font>
                        <!--ここからajax(非同期式(画面遷移なし)JavaScript & XML (Extensible Markup Language,HTMLの仲間))を記述。-->
                        <script>
                            //scriptタグは無指名だとJavaで記述しますよの意味.コメントアウトの方法も変わる。
                            function clickBtn(){
                                //Java10からvarによる型推論ができるようになったらしい。やったぜ。
                                var txt = document.getElementById("input_form").value;
                                //$('#result').text('計算結果：')
                                $.ajax({
                                    url: "{% url 'ajaxtest:write' %}",
                                    method: 'GET',
                                    data: {"input_data": txt},
                                    dataType:"text",
                                    contentType: "application/json",
                                    'success':function(response){  // 通信が成功したら動く処理で、引数には返ってきたレスポンスが入る
                                            alert(response);  // レスポンスからデータを取り出してアラート
                                            $('#result').text('黄金比：'+response);
                                        },
                                    //ここからはクロスサイトリクエストフォージェリ(forgery:偽造)を防ぐワンタイムトークン生成のコード？
                                    //ログイン状態で悪意あるサイトを踏んだとき、保存されてるCookieからパスワード抜き取られる。
                                    beforeSend: function(xhr, settings) {
                                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                            xhr.setRequestHeader("X-CSRFToken", csrf_token);
                                        }
                                        },
                                        error: function(xhr, status, error) {
                                            console.log("error");
                                        }
                                    })
                                    .done(function(data) {
                                        console.log("Success"); 
                                    });
                                    // csrf_tokenの取得に使う
                                    function getCookie(name) {
                                        var cookieValue = null;
                                        if (document.cookie && document.cookie !== '') {
                                        var cookies = document.cookie.split(';');
                                        for (var i = 0; i < cookies.length; i++) {
                                            var cookie = jQuery.trim(cookies[i]);
                                            // Does this cookie string begin with the name we want?
                                            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                            break;
                                            }
                                        }
                                        }
                                        return cookieValue;
                                    }

                                    // ヘッダにcsrf_tokenを付与する関数
                                    function csrfSafeMethod(method) {
                                        // these HTTP methods do not require CSRF protection
                                        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                                    };
                                    }
                        </script>
                        <br><br>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    <script src="{%static 'js/jquery-3.6.0.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

templates/histtest.html
<!doctype html>
<html>
        <head>
                <title>test</title>
        </head>
        <body>

            <h2>ヒストグラム描画</h2>
            <br>
            <a href="{% url 'myapp:detail' pk=file_value.id %}">CSVテーブルに戻る</a><br>
            <a href="{% url 'myapp:test2' %}">メインに戻る</a>
            <br>

            <!-- 各インスタンス属性の要素を取得 -->
            <p>アップロード日：{{ file_value.created_at }}</p>
            <p>ダウンロード：<a href="{{ file_value.upload_dir.url }}">{{file_value.file_name }}</a></p>
            <br>
            <!-- 読み込んだCSVファイルの詳細をヒストグラム化する。 -->
            <img src="data:image/png;base64, {{ response }}" width=800 height=600>
        </body>
</html>

templates/test - コピー.html
<!--bootstrapをダウンロードしないとフォントなど反映されないので注意。-->
<!--https://www.ipentec.com/document/html-css-bootstrap-grid-options-->
<!--https://webst8.com/blog/css-bootstrap4-howto/-->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width-device-width, initial-scale=1.0" />
        <title>ブラウザ上付近にタイトルが表示される</title>
        <!--以下おまじない。popper,jqueryはネットから拝借しているのでそのurlを記入しないといけない。-->
        <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-12">
                <div class="col-10">
                    <!--jumbotronは画面サイズの調整に使用する。-->
                    <div class="jumbotron mt-3" style="width: 100%;">
                        <h1 class="display-4">大見出しTOP</h1>
                        <p class="lead">ここにテキストを入力すると反映される。</p>
                        <!--hrはホリゾンタルラインの略で、横線を書く。-->
                        <hr class="my-4" />
                        <font color="green">がんばれ！！！君ならいける！！！</font><br><br>
                        <a class="btn btn-warning btn-lg m-2" role="button" href="https://en.wikipedia.org/wiki/Topological_insulator#:~:text=A%20topological%20insulator%20is%20a%20material%20that%20behaves,only%20move%20along%20the%20surface%20of%20the%20material.">専門①</a>
                        <a class="btn btn-warning btn-lg m-2" role="button" href="https://www.nist.gov/programs-projects/theory-spin-orbit-torque#:~:text=In%20the%20phenomenon%20known%20as%20spin-orbit%20torque%2C%20an,kind%20of%20magnetic%20memory%20and%20other%20electronic%20devices.">専門②</a>
                        <a class="btn btn-warning btn-lg m-2" role="button" href="C:\Users\scat\Desktop\DC2_202213517MASUDA_naiyo_05141946.pdf">ファイルテスト</a> 
                        <hr class="my-4" />
                        <p>挿入したい文字列を選択してください。</p>
                        <!--brタグは改行を表す。-->
                        <input type="text" size="50" id="input_form">
                        <button type="button" onclick="clickBtn()">送信</button>
                        <!--scriptタグはJavaとかを埋め込む。-->
                        <!-- https://qiita.com/kkkei257/items/b3292b443699ecfb148f -->
                        <script>
                            function clickBtn() {
                            var txt = document.getElementById("input_form").value;
                            $.ajax({
                                url: "{% url 'myapp:call_write_data' %}",
                                method: 'GET',
                                data: {"input_data": txt},
                                dataType: "text",
                                contentType: "application/json",
                                beforeSend: function(xhr, settings) {
                                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                                }
                                },
                                error: function(xhr, status, error) {
                                console.log("error")
                                }
                            })
                            .done(function(data) {
                                console.log("Success"); 
                            });

                            // csrf_tokenの取得に使う
                            function getCookie(name) {
                                var cookieValue = null;
                                if (document.cookie && document.cookie !== '') {
                                var cookies = document.cookie.split(';');
                                for (var i = 0; i < cookies.length; i++) {
                                    var cookie = jQuery.trim(cookies[i]);
                                    // Does this cookie string begin with the name we want?
                                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                    break;
                                    }
                                }
                                }
                                return cookieValue;
                            }

                            // ヘッダにcsrf_tokenを付与する関数
                            function csrfSafeMethod(method) {
                                // these HTTP methods do not require CSRF protection
                                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                            };
                            }
                        </script>
                        <br>
                        <br>
                        <img src="{{response}}" width=400 height=400>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    <script src="{%static 'js/jquery-3.6.0.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>
<!--
こんな表記でコメントアウト可能
-->

templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title>Web Graph</title>
</head>
<body>
    <img src='data:image/png;base64,{{ response }}'>
</body>
</html>

templates/test2.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width-device-width, initial-scale=1.0" />
        <title>CSVアップロードテスト</title>
        <!--以下おまじない。popper,jqueryはネットから拝借しているのでそのurlを記入しないといけない。-->
        <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
           <div class="container">
            <div class="row">
                <div class="col-12">
                <div class="col-10">
                    <!--jumbotronは画面サイズの調整に使用する。-->
                    <div class="jumbotron mt-3" style="width: 100%;">
                        <h1 class="display-4">ファイルアップローダ</h1>
                        <hr class="my-4" />
                        <font size="5">CSVファイルリスト</font><br>
                        <br>
                        <p>(※/freetestで黄金比の計算ページに飛びます。)</p>
                        <!-- ここから構文を書く。囲んでいれば、普通にif文など回すことができる。 -->
                        <!--<p><a href="freetest.html"><font size=6>ajaxテスト</a></p> -->
                        {% if file_obj %}
                            {% for file in file_obj %}
                                <p>
                                    {{ file.created_at }}
                                    {{ file.title }}
                                    <br>
                                    <a href="{% url 'myapp:detail' pk=file.id %}"><font size=4>詳細</font></a>
                                    &nbsp;&nbsp;<a href="{% url 'myapp:histtest' pk=file.id %}"><font size=4>  ヒストグラム表示</font></a>
                                    <br><br>
                                </p>
                            {% endfor %}
                        {%  else %}
                            <font size="4">ファイル無</font>
                        {% endif %}
                        </font>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    <script src="{%static 'js/jquery-3.6.0.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>